module TD::Types
  # Contains the content of a message.
  class MessageContent < Base
    %w[
      Text
      Animation
      Audio
      Document
      Photo
      ExpiredPhoto
      Sticker
      Video
      ExpiredVideo
      VideoNote
      VoiceNote
      Location
      Venue
      Contact
      AnimatedEmoji
      Dice
      Game
      Poll
      Story
      Invoice
      Call
      VideoChatScheduled
      VideoChatStarted
      VideoChatEnded
      InviteVideoChatParticipants
      BasicGroupChatCreate
      SupergroupChatCreate
      ChatChangeTitle
      ChatChangePhoto
      ChatDeletePhoto
      ChatAddMembers
      ChatJoinByLink
      ChatJoinByRequest
      ChatDeleteMember
      ChatUpgradeTo
      ChatUpgradeFrom
      PinMessage
      ScreenshotTaken
      ChatSetBackground
      ChatSetTheme
      ChatSetMessageAutoDeleteTime
      ForumTopicCreated
      ForumTopicEdited
      ForumTopicIsClosedToggled
      ForumTopicIsHiddenToggled
      SuggestProfilePhoto
      CustomServiceAction
      GameScore
      PaymentSuccessful
      PaymentSuccessfulBot
      GiftedPremium
      ContactRegistered
      UserShared
      ChatShared
      WebsiteConnected
      BotWriteAccessAllowed
      WebAppDataSent
      WebAppDataReceived
      PassportDataSent
      PassportDataReceived
      ProximityAlertTriggered
      Unsupported
    ].each do |type|
      autoload TD::Types.camelize(type), "tdlib/types/MessageContent/#{type}"
    end
  end
end
