module TD::Types
  # Contains notifications about data changes.
  class Update < Base
    %w[
      AuthorizationState
      NewMessage
      MessageSendAcknowledged
      MessageSendSucceeded
      MessageSendFailed
      MessageContent
      MessageEdited
      MessageIsPinned
      MessageInteractionInfo
      MessageContentOpened
      MessageMentionRead
      MessageUnreadReactions
      MessageLiveLocationViewed
      NewChat
      ChatTitle
      ChatPhoto
      ChatPermissions
      ChatLastMessage
      ChatPosition
      ChatReadInbox
      ChatReadOutbox
      ChatActionBar
      ChatAvailableReactions
      ChatDraftMessage
      ChatMessageSender
      ChatMessageAutoDeleteTime
      ChatNotificationSettings
      ChatPendingJoinRequests
      ChatReplyMarkup
      ChatBackground
      ChatTheme
      ChatUnreadMentionCount
      ChatUnreadReactionCount
      ChatVideoChat
      ChatDefaultDisableNotification
      ChatHasProtectedContent
      ChatIsTranslatable
      ChatIsMarkedAsUnread
      ChatBlockList
      ChatHasScheduledMessages
      ChatFolders
      ChatOnlineMemberCount
      ForumTopicInfo
      ScopeNotificationSettings
      Notification
      NotificationGroup
      ActiveNotifications
      HavePendingNotifications
      DeleteMessages
      ChatAction
      UserStatus
      User
      BasicGroup
      Supergroup
      SecretChat
      UserFullInfo
      BasicGroupFullInfo
      SupergroupFullInfo
      ServiceNotification
      File
      FileGenerationStart
      FileGenerationStop
      FileDownloads
      FileAddedToDownloads
      FileDownload
      FileRemovedFromDownloads
      Call
      GroupCall
      GroupCallParticipant
      NewCallSignalingData
      UserPrivacySettingRules
      UnreadMessageCount
      UnreadChatCount
      Story
      StoryDeleted
      StorySendSucceeded
      StorySendFailed
      ChatActiveStories
      StoryListChatCount
      StoryStealthMode
      Option
      StickerSet
      InstalledStickerSets
      TrendingStickerSets
      RecentStickers
      FavoriteStickers
      SavedAnimations
      SavedNotificationSounds
      SelectedBackground
      ChatThemes
      LanguagePackStrings
      ConnectionState
      TermsOfService
      UsersNearby
      AttachmentMenuBots
      WebAppMessageSent
      ActiveEmojiReactions
      DefaultReactionType
      DiceEmojis
      AnimatedEmojiMessageClicked
      AnimationSearchParameters
      SuggestedActions
      AddChatMembersPrivacyForbidden
      AutosaveSettings
      NewInlineQuery
      NewChosenInlineResult
      NewCallbackQuery
      NewInlineCallbackQuery
      NewShippingQuery
      NewPreCheckoutQuery
      NewCustomEvent
      NewCustomQuery
      Poll
      PollAnswer
      ChatMember
      NewChatJoinRequest
    ].each do |type|
      autoload TD::Types.camelize(type), "tdlib/types/Update/#{type}"
    end
  end
end
